version: '3'

services:
  nginx:
    build: .
    ports:
      - '88:80'
    volumes:
      - ./dist:/usr/local/nginx/html:ro
      - ./nginx.conf:/usr/local/nginx/conf/nginx.conf:ro
      - ./default.conf:/usr/local/nginx/conf.d/default.conf:ro
    